name: Update Subscribes

on:
  schedule:
    # 20:00 MSK == 17:00 UTC
    - cron:  '0 17 * * *'
  workflow_dispatch:  # возможность запустить вручную

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install telethon

      - name: Fetch last 2 messages and overwrite subscribes.txt
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
        run: python telegram_fetch.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add subscribes.txt
          git diff --quiet && echo "No changes to commit" || git commit -m "Daily update of subscribes.txt"
          git push
